// <auto-generated>
// Code generated by LUISGen crmHelper.json -cs EchoBot1.CRMLuisModel -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace EchoBot1.Bots
{
    public partial class CRMLuisModel: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            Accounts_AllAccounts, 
            Accounts_Top5, 
            Accounts_Total, 
            Calendar_Event, 
            Greet_Farewell, 
            Greet_Welcome, 
            Lead_Registration, 
            None, 
            Products_Top5, 
            QueryProduct, 
            Report_ActiveCases, 
            Report_PerformanceKpi, 
            Report_SalesAnalytics, 
            Report_SalesLeaderboard, 
            Search_People,
            Test333,
            SharePoint_TopLists,
            SharePoint_ListItems,
            SharePoint_AddTask,

        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] List_Name;
            public string[] Site_Name;
            public string[] Person_Name;
            public string[] Product_Name;

            // Built-in entities
            public DateTimeSpec[] datetime;

            // Instance
            public class _Instance
            {
                public InstanceData[] List_Name;
                public InstanceData[] Site_Name;
                public InstanceData[] Person_Name;
                public InstanceData[] Product_Name;
                public InstanceData[] datetime;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<CRMLuisModel>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
